<?php
namespace app\components;

use app\modules\aplicacion\models\Aplicacion;
use Yii;

class User extends \yii\web\User {

    public function afterLogin($identity, $cookieBased, $duration)
    {
        if(Yii::$app->user->can('admin')) {
            $app = Aplicacion::find()->one();
        } else {
            $app = Aplicacion::find()->where(['empresa_id' => Yii::$app->user->identity->empresa_id])->one();
        }
        $identity->aplicacion_id = $app->id;
        Yii::$app->session->set('aplicacion_id', $app->id);
        parent::afterLogin($identity, $cookieBased, $duration); // TODO: Change the autogenerated stub
    }
}