version: '3'
services:
    mysql:
        image: mysql:5.5
        env_file:
            - ./mysql.env
        volumes:
            - ./storage/mysql:/var/lib/mysql
    web:
        build: ./comandas2
        ports:
            - "8888:80"
        volumes:
            - ./comandas2:/var/www/html
            - ./storage/app:/var/www/storage/app
            - ./storage/logs:/var/www/storage/logs
