<?php

namespace app\modules\mesas\models;

use Yii;
use app\modules\aplicacion\models\Aplicacion;
use yii\web\BadRequestHttpException;

/**
 * This is the model class for table "mesas".
 *
 * @property integer $id
 * @property integer $nro_mesa
 * @property integer $aplicacion_id
 * @property string $posicion
 *
 * @property Aplicacion $aplicacion
 * @property Pedidos[] $pedidos
 */
class Mesas extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mesas';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nro_mesa', 'aplicacion_id'], 'required'],
            [['nro_mesa', 'aplicacion_id'], 'integer'],
            [['posicion'], 'string', 'max' => 200],
            [['aplicacion_id'], 'exist', 'skipOnError' => true, 'targetClass' => Aplicacion::className(), 'targetAttribute' => ['aplicacion_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'nro_mesa' => Yii::t('app', 'Nro Mesa'),
            'aplicacion_id' => Yii::t('app', 'Aplicacion ID'),
            'posicion' => Yii::t('app', 'Posicion'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAplicacion()
    {
        return $this->hasOne(Aplicacion::className(), ['id' => 'aplicacion_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPedidos()
    {
        return $this->hasMany(Pedidos::className(), ['mesas_id' => 'id']);
    }

    public function afterFind()
    {
        if($this->aplicacion_id && $this->aplicacion_id != Yii::$app->session->get('aplicacion_id'))
            throw new BadRequestHttpException();
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
