<?php

namespace app\modules\aplicacion\models;

use app\models\User;
use app\modules\mesas\models\Mesas;
use app\modules\pedidos\models\Pedidos;
use app\modules\productos\models\Productos;
use himiklab\thumbnail\EasyThumbnailImage;
use Yii;
use yii\helpers\Url;

/**
 * This is the model class for table "aplicacion".
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $empresa_id
 * @property string $subdominio
 * @property string $dominio
 * @property string $mesa_default_id
 * @property string $config
 *
 * @property Empresa $empresa
 * @property Mesas[] $mesas
 * @property Pedidos[] $pedidos
 * @property Productos[] $productos
 * @property AplicacionArchivos[] $aplicacionArchivos
 * @property UserAplicacion[] $userAplicacions
 * @property User[] $users
 */
class Aplicacion extends \yii\db\ActiveRecord
{

    public $ionic_home_image_url;
    public $ionic_home_image;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'aplicacion';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'empresa_id'], 'required'],
            [['empresa_id'], 'integer'],
            [['nombre', 'subdominio', 'dominio', 'mesa_default_id'], 'string', 'max' => 45],
            [['empresa_id'], 'exist', 'skipOnError' => true, 'targetClass' => Empresa::className(), 'targetAttribute' => ['empresa_id' => 'id']],
        ];
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['image'] = [
            'class' => 'app\behaviors\ImageBehave',
        ];
        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'nombre' => Yii::t('app', 'Nombre de la aplicación'),
            'empresa_id' => Yii::t('app', 'Empresa ID'),
            'subdominio' => Yii::t('app', 'Subdominio'),
            'dominio' => Yii::t('app', 'Dominio'),
            'mesa_default_id' => Yii::t('app', 'Mesa Default ID'),
            'config' => Yii::t('app', 'Configuración JSON'),
            'ionic_home_image' => Yii::t('app', 'Imágen de portada de la app'),
        ];
    }

    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        $fields[] = 'ionicHomeImageUrl';
        return $fields;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmpresa()
    {
        return $this->hasOne(Empresa::className(), ['id' => 'empresa_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMesas()
    {
        return $this->hasMany(Mesas::className(), ['aplicacion_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPedidos()
    {
        return $this->hasMany(Pedidos::className(), ['aplicacion_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductos()
    {
        return $this->hasMany(Productos::className(), ['aplicacion_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserAplicacions()
    {
        return $this->hasMany(UserAplicacion::className(), ['aplicacion_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])->viaTable('user_aplicacion', ['aplicacion_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAplicacionArchivos()
    {
        return $this->hasMany(AplicacionArchivos::className(), ['aplicacion_id' => 'id']);
    }

    public function getIonicHomeImageUrl()
    {
        $imagen = $this->getImage();
        /* @var $imagen \rico\yii2images\models\Image*/
        return $this->ionic_home_image_url = Yii::$app->params['baseUrl'].$imagen->getUrl();
    }

    public function beforeDelete()
    {
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
