<?php

namespace app\modules\productos\models;

use himiklab\thumbnail\EasyThumbnailImage;
use Yii;
use yii\helpers\Url;

/**
 * This is the model class for table "productos_imagenes".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $type
 * @property string $path
 * @property integer $size
 * @property integer $productos_id
 *
 * @property Productos $productos
 */
class ProductosImagenes extends \yii\db\ActiveRecord
{
    public $imageUrl;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'productos_imagenes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'productos_id'], 'required'],
            [['productos_id','size'], 'integer'],
            [['nombre','path','type'], 'string', 'max' => 45],
            [['productos_id'], 'exist', 'skipOnError' => true, 'targetClass' => Productos::className(), 'targetAttribute' => ['productos_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'nombre' => Yii::t('app', 'Nombre'),
            'producto_id' => Yii::t('app', 'Producto ID'),
            'productos_id' => Yii::t('app', 'Productos ID'),
        ];
    }

    public function fields()
    {
        $fields =  parent::fields(); // TODO: Change the autogenerated stub
        $fields[] = 'imageUrl';
        return $fields;
    }

    public function afterFind()
    {
        /*$this->imageUrl = EasyThumbnailImage::thumbnailFileUrl(
            Yii::$app->basePath.'/web/'.$this->path . '/' . $this->nombre,
            1000,
            1000,
            EasyThumbnailImage::THUMBNAIL_OUTBOUND
        );
        $this->imageUrl = str_replace('web/','',Url::to($this->imageUrl, true));*/
        $this->imageUrl = str_replace('web/','',Yii::$app->params['baseUrl'].'/'.$this->path . '/' . $this->nombre);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductos()
    {
        return $this->hasOne(Productos::className(), ['id' => 'productos_id']);
    }

    public function setNewName() {
        switch ($this->type) {
            case 'image/gif':
                $ext = '.gif';
                break;
            case 'image/jpg':
                $ext = '.jpg';
                break;
            case 'image/jpeg':
                $ext = '.jpeg';
                break;
            case 'image/png':
                $ext = '.png';
                break;
            default:
                $ext = '.jpeg';
                break;
        }
        $this->nombre = mktime().$ext;
    }
}
