<?php

namespace app\modules\productos\models;

use Yii;

/**
 * This is the model class for table "productos_opciones".
 *
 * @property integer $id
 * @property string $nombre
 *
 * @property ProductosHasProductosOpciones[] $productosHasProductosOpciones
 * @property Productos[] $productos
 * @property ProductosOpcionesHasProductos[] $productosOpcionesHasProductos
 * @property Productos[] $productos0
 */
class ProductosOpciones extends \yii\db\ActiveRecord
{
    public $productos_opciones_has_productos;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'productos_opciones';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre'], 'required'],
            [['nombre'], 'string', 'max' => 45],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'nombre' => Yii::t('app', 'Nombre'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductosHasProductosOpciones()
    {
        return $this->hasMany(ProductosHasProductosOpciones::className(), ['productos_opciones_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductos()
    {
        return $this->hasMany(Productos::className(), ['id' => 'productos_id'])->viaTable('productos_has_productos_opciones', ['productos_opciones_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductosOpcionesHasProductos()
    {
        return $this->hasMany(ProductosOpcionesHasProductos::className(), ['productos_opciones_id' => 'id']);
    }

    public function beforeDelete()
    {
        ProductosOpcionesHasProductos::deleteAll(['productos_opciones_id'=>$this->id]);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
